import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { IPodcastCard } from "@/components/PodcastCard/PodcastCard.types";
import PodcastCards from "@/components/PodcastCard/PodcastCard";
import { fetchPodcasts } from "@/store/model/service";
import { useStoreActions } from "../store";
import { useEffect } from "react";

interface IPodcastProps {
  podcasts: IPodcastCard;
}
export default function Home({ podcasts }: IPodcastProps) {
  const { feed } = podcasts;

  console.log(feed);

  // const addPodcastAction = useStoreActions(
  //   (action) => action.podcasts.addPodcast
  // );

  useEffect(() => {
    // feed.forEach(())
    console.log(feed);
  });
  return (
    <>
      <Head>
        <title>Podcaster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PodcastCards feed={feed} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const podcasts = await fetchPodcasts();

  return {
    props: {
      podcasts,
    },
  };
}
