import Head from "next/head";
import styles from "@/styles/Home.module.css";
import PodcastCards from "@/components/PodcastCard/PodcastCard";
import { fetchPodcasts } from "@/store/model/service";
import { useStoreActions, useStoreState } from "../store";
import { useCallback, useEffect } from "react";
import { calculateDays } from "@/utils";

export default function Home() {
  const podcastActions = useStoreActions((action) => action.podcasts);
  const state = useStoreState((state) => state.podcasts);

  const fetchData = useCallback(async () => {
    podcastActions.setIsLoading(true);
    const totalDays = calculateDays(state.lastFechted);

    try {
      if (state.firstTimeFetch === false || totalDays >= 1) {
        podcastActions.setFirstTimeFetch(true);
        const podcasts = await fetchPodcasts();
        if (podcasts) {
          podcastActions.setPodcasts(podcasts);
          podcastActions.setLastFetched(new Date());
        }
      }
      podcastActions.setIsLoading(false);
    } catch (e: any) {
      console.error(e.message);
    }
  }, [podcastActions, state.lastFechted, state.firstTimeFetch]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);
  return (
    <>
      <Head>
        <title>Podcaster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {state.podcasts && !state.isLoading && (
        <main className={styles.main}>
          <PodcastCards feed={state.podcasts.feed} />
        </main>
      )}
    </>
  );
}
