import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { TOP_100_ITUNES_PODCASTS_URL } from "./constants";
import { IPodcastCard } from "@/components/PodcastCard/PodcastCard.types";
import PodcastCard from "@/components/PodcastCard/PodcastCard";

const inter = Inter({ subsets: ["latin"] });

interface IPodcastProps {
  podcasts: IPodcastCard;
}
export default function Home({ podcasts }: IPodcastProps) {
  const { feed } = podcasts;
  return (
    <>
      <Head>
        <title>Podcaster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PodcastCard feed={feed} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(TOP_100_ITUNES_PODCASTS_URL);

  const podcasts = await res.json();

  return {
    props: {
      podcasts,
    },
  };
}
